#!/bin/bash
##ssh -l yanghao 192.168.1.48

	set user yanghao@
	set passwd yanghao123
	set remote_ip 192.168.1.48
        ssh $user$remote_ip
	expect "password:" 
        set timeout 300;
	send "\$passwd"	

function root
{
	set action2 root
	set rootpassword Lajoin
	set timeout 50;
	spawn su \$action2
	expect "password:" 
	send "$rootpassword"	
		interact 
}
myssh &&
root 
exit
